import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { poppins, roboto } from 'fonts';
import './globals.css';
import MainNav from 'components/common/navbars/MainNav';



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <MainNav />
          <main>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
