import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { poppins, roboto } from 'fonts';
import './globals.css';



export const metadata: Metadata = {
  title: 'Ecom',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="system">
            {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
