import { Suspense } from 'react';
import type { Metadata } from 'next';
import LoadingAnimation from 'components/common/LoadingAnimation';
import Search from 'components/common/Search';
import MainNavServer from 'components/common/navbars/MainNav.server';
import Footer from 'components/common/Footer';

export const metadata: Metadata = {
  title: 'Ecom Website',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Suspense fallback={<LoadingAnimation />}>
        <MainNavServer />
      </Suspense>
      <main className='min-h-[60vh]'>{children}</main>
      <Search />
      <Footer />
    </>
  );
}
